blog/urls.py
from django.conf.urls import url, include
from . import views



urlpatterns = [
     url(r'^$', views.Blog.as_view(), name='blog'),
     url(r'^details/(?P<id>\d+)/$', views.blogdetail, name='blog-detail'),
   
]

houses/urls.py
from django.conf.urls import url, include
from . import views
from django.contrib.auth.models import User


urlpatterns = [
    url(r'^addlisting/$', views.addlisting, name='addlisting'),
    url(r'^listing/details/(?P<id>\d+)/$', views.listbyuserdetails, name='detail'),
    url(r'^listing/details/(?P<pk>\d+)/editlist2$', views.editlist2, name='editlist2'),
    url(r'^listing/details/(?P<pk>\d+)/deletelist$', views.deletelist, name='deletelist'),
    url(r'^userlist/', views.UserListView.as_view(), name='userlist'),
    url(r'^alllisting/', views.alllisting.as_view(), name='alllisting'),
    url(r'^phone/(?P<id>\d+)$', views.phone, name='phone'),
    url(r'^vipsearch$', views.vipSearch, name='vipSearch'),
    url(r'^success/(?P<id>\d+)$', views.phone, name='phone'),
    url(r'^vipsearchuser/', views.VipListView.as_view(), name='viplist'),
   
    url(r'^vip/details/(?P<id>\d+)/$', views.vipbyuserdetails, name='vip-detail'),
    url(r'^vipdetails/(?P<pk>\d+)', views.deletelist2, name='deletelist2'),
    
   
]

paystack/urls.py
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt

from . import settings
from . import views
urlpatterns = [
    url(r'^verify-payment/(?P<order>[\w.@+-]+)/$',
        views.verify_payment, name='verify_payment'),
    url(r'^failed-verification/(?P<order_id>[\w.@+-]+)/$',
        views.failure_redirect_view, name='failed_verification'),
    url(r'^successful-verification/(?P<order_id>[\w.@+-]+)/$',
        views.success_redirect_view,
        name='successful_verification'),
    url(r'^failed-page/$',
        views.TemplateView.as_view(template_name='paystack/failed-page.html'), name='failed_page'),
    url(r'^success-page/$',
        views.TemplateView.as_view(template_name='paystack/success-page.html'), name='success_page'),
    url(r'^webhook/$', csrf_exempt(views.webhook_view), name='webhook'),
]

ywala/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    url(r'^houses/', include('houses.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^messages/', include('postman.urls', namespace='postman')),
    url(r'^', include('initial.urls')),
    url(r'^paystack/', include(('paystack.urls','paystack'),namespace='paystack')),
]

if settings.DEBUG:    
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

houses/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from datetime import datetime

  

class Myhouses(models.Model):
    
    Available = 'A'
    Not_Available = 'NA'
    Reserved = 'R'
    Availability = (
        (Available, 'Available'),
        (Not_Available, 'Not_Available'),
        (Reserved, 'Reserved')
    )


    private = 'Private'
    Shared = 'Shared'
    toilet = (
        (private, 'private'),
        (Shared, 'Shared'),
    )


    Yes = 'Yes'
    No = 'No'
    water = (
        (Yes, 'Yes'),
        (No, 'No'),
    )

    Yes = 'Yes'
    No = 'No'
    fence = (
        (Yes, 'Yes'),
        (No, 'No'),
    )

    Yes = 'Yes'
    No = 'No'
    park = (
        (Yes, 'Yes'),
        (No, 'No'),
    )



    Flat = 'Flat'
    Self_contained = 'Self Contain'
    Bungalow = 'Bungalow'
    Mini_flat = 'Mini Flat'
    Duplex = 'Duplex'
    Student_lodge = 'Student Lodge'
    Student_hostel = 'Student Hostel'
    Others = 'Others'
    Looking_for_roommate = 'Looking for roommate'
    Room = (
        (Flat, 'Flat'),
        (Self_contained, 'Self contained'),
        (Bungalow, 'Bungalow'),
        (Mini_flat, 'Mini flat'),
        (Student_lodge, 'Student lodge'),
        (Student_hostel, 'Student hostel'),
        (Others, 'Others'),
        (Looking_for_roommate, 'Looking for roommate'),
    )


    Abuja = 'Abuja'
    Abia = 'Abia'
    Adamawa = 'Adamawa'
    Akwa_ibom = 'Akwa Ibom'
    Anambra = 'Anambra'
    Bauchi = 'Bauchi'
    Bayelsa = 'Bayelsa'
    Benue = 'Benue'
    Borno = 'Borno'
    Cross_River = 'Cross River'
    Delta = 'Delta'
    Ebonyi = 'Ebonyi'
    Edo = 'Edo'
    Ekiti = 'Ekiti'
    Enugu = 'Enugu'
    Gombe = 'Gombe'
    Imo = 'Imo'
    Jigawa = 'Jigawa'
    Kaduna = 'Kaduna'
    Kano = 'Kano'
    Katsina = 'Katsina'
    Kebbi = 'Kebbi'
    Kogi = 'Kogi'
    Kwara = 'Kwara'
    Lagos = 'Lagos'
    Nasarawa = 'Nasarawa'
    Niger = 'Niger'
    Ogun = 'Ogun'
    Ondo = 'Ondo'
    Osun = 'Osun'
    Oyo = 'Oyo'
    Plateau = 'Plateau'
    Rivers = 'Rivers'
    Sokoto = 'Sokoto'
    Taraba = 'Taraba'
    Yobe = 'Yobe'
    Zamfara = 'Zamfara'
    
    States = (
        (Abuja, 'Abuja'),
        (Abia, 'Abia'),
        (Adamawa, 'Adamawa'),
        (Akwa_ibom, 'Akwa ibom'),
        (Anambra, 'Anambra'),
        (Bauchi, 'Bauchi'),
        (Bayelsa, 'Bayelsa'),
        (Benue, 'Benue'),
        (Borno, 'Borno'),
        (Cross_River, 'Cross River'),
        (Delta, 'Delta'),
        (Ebonyi, 'Ebonyi'),
        (Edo, 'Edo'),
        (Ekiti, 'Ekiti'),
        (Enugu, 'Enugu'),
        (Gombe, 'Gombe'),
        (Imo, 'Imo'),
        (Jigawa, 'Jigawa'),
        (Kaduna, 'Kaduna'),
        (Kano, 'Kano'),
        (Katsina, 'Katsina'),
        (Kebbi, 'Kebbi'),
        (Kogi, 'Kogi'),
        (Kwara,'Kwara'),
        (Lagos,'Lagos'),
        (Nasarawa, 'Nasarawa'),
        (Niger,  'Niger'),
        (Ogun, 'Ogun'),
        (Ondo, 'Ondo'),
        (Osun,  'Osun'),
        (Oyo, 'Oyo'),
        (Plateau, 'Plateau'),
        (Rivers, 'Rivers'),
        (Sokoto, 'Sokoto'),
        (Taraba, 'Taraba'),
        (Yobe, 'Yobe'),
        (Zamfara, 'Zamfara'),

    )

    time = models.DateTimeField(default = datetime.now, blank = True)
    name_of_accomodation = models.CharField(max_length=20)
    type_of_apartment = models.CharField(max_length=20, choices=Room, )
    Number_of_rooms = house_rent = models.IntegerField()
    house_rent = models.IntegerField()
    Landlord_number =models.CharField(max_length=200)
    availability = models.CharField(max_length=2, choices=Availability, default=Available,)
    State = models.CharField(max_length=20, choices=States, )
    City_or_town = models.CharField(max_length=200)
    Street = models.CharField(max_length=200)
    Size_of_room = models.CharField(max_length=200)
    Available_from = models.CharField(max_length=200)
    Toilet = models.CharField(max_length=20, choices=toilet,)
    Running_water = models.CharField(max_length=20, choices=water)
    Fenced = models.CharField(max_length=20, choices=fence)
    Parking_space = models.CharField(max_length=20, choices=park,)
    Account_name = models.CharField(max_length=200)
    Account_number = models.IntegerField()
    Payment_status = models.TextField(default='Not Paid')

    nearest_institution = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    house_image = models.ImageField()
    house_image2 = models.ImageField()
    house_image3 = models.ImageField()
    house_image4 = models.ImageField()
    house_image5 = models.ImageField()
    house_image6 = models.ImageField()
    house_image7 = models.ImageField(null=True, blank=True)
    house_image8 = models.ImageField( null=True, blank=True )
    house_image9 = models.ImageField( null=True, blank=True)
    house_image10 = models.ImageField( null=True, blank=True )
    house_image11 = models.ImageField( null=True, blank=True)
    house_image12 = models.ImageField( null=True, blank=True )
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name='author')

    def __str__(self):
        return self.name_of_accomodation

    def get_absolute_url(self):
        return reverse('search-detail', args=[str(self.id)])

    class Meta:
        ordering = ["-time"]


class Vip(models.Model):
    Flat = 'Flat'
    Self_contained = 'Self Contain'
    Bungalow = 'Bungalow'
    Mini_flat = 'Mini Flat'
    Duplex = 'Duplex'
    Student_lodge = 'Student Lodge'
    Student_hostel = 'Student Hostel'
    Others = 'Others'
    Looking_for_roommate = 'Looking for roommate'

    Room = (
        (Flat, 'Flat'),
        (Self_contained, 'Self contained'),
        (Bungalow, 'Bungalow'),
        (Mini_flat, 'Mini flat'),
        (Student_lodge, 'Student lodge'),
        (Student_hostel, 'Student hostel'),
        (Others, 'Others'),
        (Looking_for_roommate, 'Looking for roommate'),
    )


    Abuja = 'Abuja'
    Abia = 'Abia'
    Adamawa = 'Adamawa'
    Akwa_ibom = 'Akwa Ibom'
    Anambra = 'Anambra'
    Bauchi = 'Bauchi'
    Bayelsa = 'Bayelsa'
    Benue = 'Benue'
    Borno = 'Borno'
    Cross_River = 'Cross River'
    Delta = 'Delta'
    Ebonyi = 'Ebonyi'
    Edo = 'Edo'
    Ekiti = 'Ekiti'
    Enugu = 'Enugu'
    Gombe = 'Gombe'
    Imo = 'Imo'
    Jigawa = 'Jigawa'
    Kaduna = 'Kaduna'
    Kano = 'Kano'
    Katsina = 'Katsina'
    Kebbi = 'Kebbi'
    Kogi = 'Kogi'
    Kwara = 'Kwara'
    Lagos = 'Lagos'
    Nasarawa = 'Nasarawa'
    Niger = 'Niger'
    Ogun = 'Ogun'
    Ondo = 'Ondo'
    Osun = 'Osun'
    Oyo = 'Oyo'
    Plateau = 'Plateau'
    Rivers = 'Rivers'
    Sokoto = 'Sokoto'
    Taraba = 'Taraba'
    Yobe = 'Yobe'
    Zamfara = 'Zamfara'
    
    States = (
        (Abuja, 'Abuja'),
        (Abia, 'Abia'),
        (Adamawa, 'Adamawa'),
        (Akwa_ibom, 'Akwa ibom'),
        (Anambra, 'Anambra'),
        (Bauchi, 'Bauchi'),
        (Bayelsa, 'Bayelsa'),
        (Benue, 'Benue'),
        (Borno, 'Borno'),
        (Cross_River, 'Cross River'),
        (Delta, 'Delta'),
        (Ebonyi, 'Ebonyi'),
        (Edo, 'Edo'),
        (Ekiti, 'Ekiti'),
        (Enugu, 'Enugu'),
        (Gombe, 'Gombe'),
        (Imo, 'Imo'),
        (Jigawa, 'Jigawa'),
        (Kaduna, 'Kaduna'),
        (Kano, 'Kano'),
        (Katsina, 'Katsina'),
        (Kebbi, 'Kebbi'),
        (Kogi, 'Kogi'),
        (Kwara,'Kwara'),
        (Lagos,'Lagos'),
        (Nasarawa, 'Nasarawa'),
        (Niger,  'Niger'),
        (Ogun, 'Ogun'),
        (Ondo, 'Ondo'),
        (Osun,  'Osun'),
        (Oyo, 'Oyo'),
        (Plateau, 'Plateau'),
        (Rivers, 'Rivers'),
        (Sokoto, 'Sokoto'),
        (Taraba, 'Taraba'),
        (Yobe, 'Yobe'),
        (Zamfara, 'Zamfara'),

    )

    type_of_apartment = models.CharField(max_length=20, choices=Room, )
    Number_of_rooms = models.IntegerField()
    State = models.CharField(max_length=20, choices=States, )
    City_or_town = models.CharField(max_length=200)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name='authorVip')

class paid(models.Model):
    client = models.CharField(max_length=20, )
    amount = models.IntegerField()
    accomodation = models.CharField(max_length=200 )

class Paids(models.Model):
    amount = models.IntegerField()
    myRef = models.TextField()
    username = models.TextField()
    

houses/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Myhouses, Vip

class MyHouseEditForm(forms.ModelForm):    
    class Meta:        
        model = Myhouses   
        labels = {
            'Landlord_number': "Landlord or House Agent's Phone Number"
        }     
        fields = ('name_of_accomodation', 'type_of_apartment','Parking_space', 'Number_of_rooms','Fenced', 'Running_water', 'house_rent', 'Landlord_number','Toilet', 'availability', 'State','Available_from', 'City_or_town', 'Size_of_room', 'nearest_institution', 'description', 'Street', 'house_image', 'house_image2', 'house_image3', 'house_image4', 'house_image5', 'house_image6', 'house_image7', 'house_image8', 'house_image9', 'house_image10', 'house_image11', 'house_image12', 'Account_number', 'Account_name') 


class VipForm(forms.ModelForm):    
    class Meta:        
        model = Vip  
        fields = ('type_of_apartment', 'Number_of_rooms', 'State', 'City_or_town') 

houses/views.py
from django.http import HttpResponse 
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth import authenticate, login 
from .forms import MyHouseEditForm, VipForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from . models import Myhouses, paid, Paids, Vip
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from django.contrib.auth.models import User
from django.forms import modelformset_factory
from django.template import RequestContext
from paystack.signals import payment_verified
from django.dispatch import receiver
from paystack.signals import event_signal
import re


@login_required
def addlisting(request):    
    if request.method == 'POST': 
        house_form = MyHouseEditForm(request.POST, files=request.FILES, )
        if house_form.is_valid():    
            Houses = house_form.save(commit=False)
            Houses.author=request.user
            Houses.Payment_status = "Not Paid"
            Houses.save()
            id = Houses.pk
            messages.success(request, 'Listing Created Succesfully successfully')
            return redirect('detail', id)           
    else:        
        house_form = MyHouseEditForm()
    return render(request, 'houses/addlisting.html', {'house_form':house_form},  )


class UserListView(LoginRequiredMixin,generic.ListView):
    model = Myhouses
    template_name ='houses/ListingByUser.html'
    paginate_by = 9
    
    
    def get_queryset(self):
        return Myhouses.objects.filter(author=self.request.user)

class VipListView(LoginRequiredMixin,generic.ListView):
    model = Vip
    template_name ='houses/vipByUser.html'
    paginate_by = 9
    
    
    def get_queryset(self):
        return Vip.objects.filter(author=self.request.user)


class alllisting(LoginRequiredMixin,generic.ListView):
    model = Myhouses
    template_name ='houses/alllisting.html'
    paginate_by = 2




@login_required
def listbyuserdetails(request, id):
    house_list1 = Myhouses.objects.get(id = id)

    context = {
        'house_list1':house_list1
    }

    return render(request, 'houses/ListingByUserDetails.html', context)


@login_required
def vipbyuserdetails(request, id):
    house_list1 = Vip.objects.get(id = id)

    context = {
        'house_list1':house_list1
    }

    return render(request, 'houses/vip-details.html', context)

@login_required
def editlist2(request, pk):
    house_edit = get_object_or_404(Myhouses, pk = pk)
    if request.method == 'POST': 
        house_form = MyHouseEditForm(request.POST, files=request.FILES, instance=house_edit)
        if house_form.is_valid():    
            Houses = house_form.save(commit=False)
            Houses.save()
            messages.success(request, 'Listing Updated Succesfully')
            return redirect('editlist2', pk) 
        else:
            messages.success(request, 'Error Updating Listing')
            return redirect('editlist2', pk)         
    else:        
        house_form = MyHouseEditForm(instance=house_edit)
    return render(request, 'houses/editlist.html', {'house_form':house_form, 'house_edit': house_edit},  )

@login_required
def deletelist(request, pk):
    house_delete = get_object_or_404(Myhouses, pk = pk)
    if request.user == house_delete.author:
        house_delete.delete()
        messages.success(request, 'Listing Deleted Succesfully')
        return redirect('userlist')
    else:
        return HttpResponse('unauthorized ACTIVITY')

@login_required
def deletelist2(request, pk):
    house_delete = get_object_or_404(Vip, pk = pk)
    if request.user == house_delete.author:
        house_delete.delete()
        messages.success(request, 'Search Deleted Succesfully')
        return redirect('viplist')
    else:
        return HttpResponse('unauthorized ACTIVITY')



@login_required
def phone(request, id):
    house_list1 = Myhouses.objects.get(id = id)

    context = {
        'house_list1':house_list1
    }

    return render(request, 'houses/phone.html', context)

@login_required
def vipSearch(request):
    if request.method == 'POST': 
        vip_form = VipForm(request.POST )
        if vip_form.is_valid():    
            vip = vip_form.save(commit=False)
            vip.author=request.user
            vip.save()
            messages.success(request, 'Information saved successfully')
            return redirect('dashboard')           
    else:        
        vip_form = VipForm()
    return render(request, 'houses/vip.html', {'vip_form': vip_form})







@receiver(event_signal)
def on_event_received(sender, event, data, **kwargs):
    a = 'greatgodevent'
    b = 'jesusevent'
    c = int(4)
    d = data['metadata']['referrer']
    e = (re.findall('\d+', d ))
    id = int(e[0])
    g = 'Paid'
    editme = get_object_or_404(Myhouses, pk = id)
    editme.Payment_status = g
    editme.save()
    Paids.objects.create(myRef= event, amount=c, username=id, )
    return HttpResponse(status=200)

   

houses/templates/houses/ListingByUser.html
{% extends "base.html" %}
{% load static %}
<link rel='stylesheet' href='{% static "account/styles.css" %}'>
{% block content %}
    <section id='userlisting1'>
        
        <div class='outeruser'>
            <div class='userlisting'>
                <br>
                    {% if messages %}
                    <div class="alert alert-success">
                        <p>    
                            {% for message in messages %}          
                                {{ message|safe }}          
                            {% endfor %}  
                        </p>
                    </div>                     
                {% endif %}
                <ul class='divider'>
                    <p style=" font-size: 25px; color:#666666; padding-top: 24px;">My Listings</p>
                    {% if myhouses_list %}
                    <div class='row'>
                    {% for house in myhouses_list  %}
                    <div class='col-sm-4' >
                        <div id='myinner'>
                            
                            <li><img src='{{house.house_image2.url}}'   class='responsive'></li>
                            <br>
                            <div class='userpost'>
                                <div class='rightguy'>
                                    <li> {{house.name_of_accomodation}}</li>
                                    <li><img src="{% static 'account/bed1.png' %}" width='17px' height='17px'>&nbsp{{house.Number_of_rooms}}</li>
                                </div>
                                <div class='leftguy'>
                                    <li><li><img src="{% static 'account/loc2.png' %}" width='20px' height='20px' > &nbsp{{house.State}}</li>
                                    <li><img src="{% static 'account/naira1.png' %}" width='20px' height='20px' >&nbsp{{house.house_rent}}</li>
                                </div>
                                
                            </div>
                            <div class='centreguy'>
                                <a href="{% url 'detail' house.id %}"><button class='button_4' >View more</button></a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    {% else %}
                    <div style='font-size: 16px;'>No listing to display</div><br>
                    <br>
                    </div>
                   
                    </ul>
                    {% endif %}
            </div>
            {% if is_paginated %}
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
        {% endif %}
            
        </div>
    </section>
{% endblock %}

houses/templates/houses/alllisting.html
{% for house in myhouses_list  %}
                    <div class='text-center' id='myinner'>
                    <li><img src='{{house.image.url}}'width='150px' height="150px" style='border-radius:50%' ></li>
                    <li><strong>Name of Accomodation:</strong> {{house.name_of_accomodation}}</li>
                    <li><strong>Type of room:</strong>{{house.type_of_room}}</li>
                    <li><strong>Location:</strong>{{house.location}}</li>
                    <li><strong>House Rent:</strong>{{house.house_rent}}</li>
                    <a href="{% url 'detail' house.id %}"><button class='button_1' id='learnmore'>Learn more</button></a>
{% endfor %}

{% if is_paginated %}
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
        {% endif %}

houses/templates/houses/phone.html
{% load static %}
<link rel='stylesheet' href='{% static "account/styles.css" %}'> 
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Tangerine">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Ubuntu">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Ubuntu:italic">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
<section id='lshowcase'>
    <br>
    <br>
    <br>
    <br>
    <br>
    
    <br>
<div class='lcontainer' style='font-size:20px;'>
        
        <strong>Phone Number: </strong>{{house_list1.Landlord_number}}<br><br>
        <a href="{% url 'search-detail' house_list1.id %}"> <button class='btn btn-success'>Go Back</button></a>
</div>
</section>

houses/templates/houses/vip-details.html
{% extends "base.html" %}  
{% load static %}
{% load bootstrap3 %}
<link rel='stylesheet' href='{% static "account/styles.css" %}'>
{% block content %}     
    <div id='addhouse'>
        <br>
        <div class='addshow'>
            <p>Are you sure you want to delete This Search?</p>
            <a href="{% url 'deletelist2' pk=house_list1.pk %}">Yes!</a>
            <br><br> <br> 
        </div>
    </div>
{% endblock %}




 

houses/templates/houses/vip.html
{% extends "base.html" %}  
{% load static %}
{% load bootstrap3 %}
<link rel='stylesheet' href='{% static "account/styles.css" %}'>
{% block content %}     
    <div id='addhouse'>
        <br>
        <div class='addshow'>
                {% if messages %}
                            <div class="alert alert-success">
                                <p>    
                                    {% for message in messages %}          
                                        {{ message|safe }}          
                                    {% endfor %}  
                                </p>
                            </div>                     
                        {% endif %}
            <br>
            <h1 style=" font-size: 30px; color:#666666;">VIP search</h1>  
            
            <div id='vipText'>
                <div id='vipText2'>
                    <p>Dear {{ request.user.first_name }}</p>
                    <p>Our priority is making the process of finding an apartment simple and easy for you. Therefore, we do the search for you while you relax</p>
                    <p>Create a search profile and we will send you an email when a new listing mathces your search criteria</p>
                    <p>Let us do the work for you</p>
                </div>
            </div>
            <br><br><br> 
             <a href='{% url "viplist" %}'><button class='btn btn-success'>View Your Saved Searches</button></a><br>
            <h3>Add a New Search</h3>
             <form method="POST" class="post-form" >
                    {% csrf_token %}    
                {% load bootstrap %}
                {{ vip_form|bootstrap}}   
                    
                <p><button type="submit" class='btn btn-success'>Save Changes</button></p>  
            </form>
            <br>
        </div>
    </div>
{% endblock %}




 

houses/templates/houses/vipByUser.html
{% extends "base.html" %}
{% load static %}
<link rel='stylesheet' href='{% static "account/styles.css" %}'>
{% block content %}
    <section id='userlisting1'>
        
        <div class='outeruser'>
            <div class='userlisting'>
                <br>
                    {% if messages %}
                    <div class="alert alert-success">
                        <p>    
                            {% for message in messages %}          
                                {{ message|safe }}          
                            {% endfor %}  
                        </p>
                    </div>                     
                {% endif %}
            
                    <p style=" font-size: 25px; color:#666666; padding-top: 24px;">Saved VIp Searches</p>
                    {% if vip_list %}
                    <div class='row'>
                    {% for house in vip_list  %}
                    <div class='well' style='padding-bottom:100px'>
                        <div class = 'vip-show'>
                            <div class ='vip-show-left'>
                                {{house.type_of_apartment}}<br>
                                Rooms:&nbsp{{house.Number_of_rooms}}<br><br>
                                <a href="{% url 'vip-detail' house.id %}"><button class='btn btn-danger' >Delete</button></a>
            
                            </div>
                            <div class ='vip-show-right'>
                                {{house.State}}<br>
                                {{house.City_or_town}}
                                
                            </div>
                        </div>
                    </div><br>



    
                    {% endfor %}
                    {% else %}
                    <div style='font-size: 16px;'>No listing to display</div><br>
                    <br>
                    </div>
                   
                    
                    {% endif %}
            </div>
            {% if is_paginated %}
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
        {% endif %}
            
        </div>
    </section>
{% endblock %}