blog/urls.py
from django.conf.urls import url, include
from . import views



urlpatterns = [
     url(r'^$', views.Blog.as_view(), name='blog'),
     url(r'^details/(?P<id>\d+)/$', views.blogdetail, name='blog-detail'),
   
]

paystack/urls.py
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt

from . import settings
from . import views
urlpatterns = [
    url(r'^verify-payment/(?P<order>[\w.@+-]+)/$',
        views.verify_payment, name='verify_payment'),
    url(r'^failed-verification/(?P<order_id>[\w.@+-]+)/$',
        views.failure_redirect_view, name='failed_verification'),
    url(r'^successful-verification/(?P<order_id>[\w.@+-]+)/$',
        views.success_redirect_view,
        name='successful_verification'),
    url(r'^failed-page/$',
        views.TemplateView.as_view(template_name='paystack/failed-page.html'), name='failed_page'),
    url(r'^success-page/$',
        views.TemplateView.as_view(template_name='paystack/success-page.html'), name='success_page'),
    url(r'^webhook/$', csrf_exempt(views.webhook_view), name='webhook'),
]

ywala/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    url(r'^houses/', include('houses.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^messages/', include('postman.urls', namespace='postman')),
    url(r'^', include('initial.urls')),
    url(r'^paystack/', include(('paystack.urls','paystack'),namespace='paystack')),
]

if settings.DEBUG:    
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from datetime import datetime


class Post(models.Model):
    title = models.CharField(max_length=20)
    body = models.TextField()
    time = models.DateTimeField(default = datetime.now, blank = True)

    def __str__(self):
        return self.title
    class Meta:
        ordering = ["-time"]

blog/views.py
from django.shortcuts import render
from . models import Post
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.contrib.auth.decorators import login_required





class Blog(generic.ListView):
    model = Post
    template_name ='blog/blogIndex.html'
    paginate_by = 6
    


def blogdetail(request, id):
    blog_details = Post.objects.get(id = id)

    context = {
        'blog_details':blog_details
    }

    return render(request, 'blog/blog-details.html', context)

blog/templates/blog/blog-details.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap3 %}
{% load spacing %}
<link rel='stylesheet' href='{% static "account/styles.css" %}'>
{% block content %}
    <div class='blog-home'>
        <div class='blog-home-2'>
                <div class='custom-well' >
                        <h2>{{blog_details.title}}</h2><br>
                        
                            <p class='blog-body-details'> {{ blog_details.body|keep_spacing }}</p> 

                           
                </div><br>
    
        </div>
    </div>
{% endblock %}
   




 

blog/templates/blog/blogIndex.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap3 %}
{% load spacing %}
<link rel='stylesheet' href='{% static "account/styles.css" %}'>
{% block content %}
    <div class='blog-home'>
        <div class='blog-home-2'>
            <h2>Ywala Blog</h2><br>
                {% for blog in post_list  %}
                <div class='custom-well' >
                        <h3>{{blog.title}}</h3><br>
                        <div class='blog-body'>
                            <p>{{ blog.body|keep_spacing }} }}</p> 
                        </div><br>
                        <a href="{% url 'blog-detail' blog.id %}"><button class='btn btn-primary' >Continue Reading</button></a>
    
                </div><br>

                {% endfor %}
            
        </div>
    </div>
{% endblock %}
   




 